<!DOCTYPE html>
<html lang="en">

<head><?php include('includes/headScript.php');
        ?>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="css/leaders.css?v=5" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <!-- Banner -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Catamaran:wght@400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@700&display=swap" rel="stylesheet">
    <title>MBFX GLOBAL</title><?php $page = 'copyTrading';
                                ?>
</head>

<body><?php include('includes/header.php');
        ?><!-- Banner -->
    <section class="banner">
        <div class="row w-100">
            <div class="container">
                <div class="col-md-6 col-lg-6 col-sm-12">
                    <h1>Empower Your Trading with Top Leaders - Where Success is Multiplied</h1><a target="_blank" href="#" class="btn btn-primary btn-secondary-outline">About US</a>
                </div>
            </div>
        </div>
    </section>

    <section id="elite">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 col-md-6 text-center">
                    <div>
                        <img class="" src="assets/leaders/copytrade.png" alt="">
                    </div>
                </div>
                <div class="col-12 col-md-6 reward-content">

                    <h1>Maximize Your Profits With Elite <span class="text-green">Traders</span></h1>
                    <p>By mirroring the trading strategies of professionals, you can potentially achieve more consistent returns and gain valuable insights into the financial markets. Copy trading allows you to tap into the expertise of experienced traders globally, making it easier to navigate the complexities of trading and potentially increase your chances of success. Filter the traders who meet your needs.</p>

                </div>
            </div>


        </div>
    </section>

    <section class="footerBottom pb-0">
        <div class="container my-4">

            <div class="row align-items-center justify-content-center">
                <div class="col-12 col-md-12 col-lg-6 pe-md-6"><a href="index.php"><img class="logo-image" src="https://mbfx.co/assets/header/mbfx-logo.png" /></a>
                    <p class="footer-desclimber">Please be aware that all investments are subject to market fluctuations. The financial markets can be highly unpredictable,
                        and past performance is not a guarantee of future results. Under no circumstances shall MBFX have any liability to any person or entity for any direct,
                        indirect,
                        special,
                        consequential,
                        or incidental damages whatsoever. We urge you to carefully evaluate these risks with your investment objectives and risk tolerance before participating in our copy trading services. There may be a chance that you may be following/copying the trading decisions of possibly inexperienced/unprofessional traders,
                        or traders whose ultimate purpose or intention,
                        or financial status may differ from yours. The past performance of an MBFX fund manager is not a reliable indicator of his future performance. Content on MBFX's social trading platform is generated by members of its community and does not contain advice or recommendations by or on behalf of MBFX.</p>
                </div>
                <div class="col-12 col-md-6 col-lg-2 col-sm-12">
                    <ul class="list-group menu">
                        <li class="list-group-item list-items"><a href=""><strong>Contact Us:</strong></a></li>
                        <li class="list-group-item list-items"><a href="">Mail: support@mbfx.co </a></li>
                        <li class="list-group-item list-items"><a href="">Call:+44 20 3290 5333 </a></li>
                        <li class="list-group-item list-items">Whatsapp:+447927555692</li>
                    </ul>
                </div>
                <div class="col-12 col-md-6 col-lg-4 col-sm-12">
                    <ul class="list-group mb-4 mb-md-0 menu">
                        <li class="list-group-item list-items mb-4"><strong>SIGN UP FOR EMAIL UPDATES</strong></li>
                        <li class="list-group-item list-items">
                            <div class="col-12">
                                <div class="input-group"><input type="email" class="form-control" placeholder="Your e-mail Address" aria-label="email" aria-describedby="basic-addon2"><span class="input-group-text btn btn-primary btn-secondary" id="basic-addon2">Subscribe</span></div>
                            </div>
                        </li>
                        <li class="list-group-item list-items mt-4">Sign up with your mail address to receive update and news.</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <div class="footerText">
        <div class="container-fluid">
            <div class="row">
                <div class="form-link-sec col-12 col-md-4 col-lg-4 d-flex justify-content-center">
                    <ul class="d-inline-flex">
                        <li class="col-3 px-3"><a href="https://www.facebook.com/mbfxglobal/?ref=pages_you_manage"><i class="fa-brands fa-2xl fa-square-facebook" style="color: #767b80;"></i></a></li>
                        <li class="col-3 px-3"><a href="https://www.instagram.com/mbfxglobal/"><i class="fa-brands fa-square-instagram fa-2xl" style="color: #767b80;"></i></a></li>
                        <li class="col-3 px-3"><a href="https://twitter.com/mbfx_global"><i class="fa-brands fa-square-twitter fa-2xl" style="color: #767b80;"></i></a></li>
                        <li class="col-3 px-3"><a href="https://youtube.com/c/MBFXglobal"><i class="fa-brands fa-square-youtube fa-2xl" style="color: #767b80;"></i></a></li>
                    </ul>
                </div>
                <div class="col-12 col-md-8 col-lg-8 d-flex justify-content-center">
                    <ul class="d-inline-flex legal">
                        <li>Terms of Services</li>
                        <li>Privacy Policy </li>
                        <li>Risk Disclaimer</li>
                        <li>Conflict of Interest</li>
                        <li>Declaration of Consent</li>
                        <li>End-User License Agreements</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>